### ISSUE TITLE
Unable to run with storybook

### ISSUE THREAD

**Issue by AndreyYolkin** [userquin/vuetify-nuxt-module#179]
## My setup:
- Operating System: `Darwin`
- Node Version:     `v20.5.0`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `pnpm@8.10.5`
- Builder:          `-`
- User Config:      `modules`, `i18n`, `devtools`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0`, `vuetify-nuxt-module@0.8.0`
- Build Modules:    `-`

## Reproduction
https://github.com/AndreyYolkin/storybook-vuetify-issue

## Description
Thank you for your titanic work on building this module. I've tried to add storybook into my project, but for some reasons vuetify works in dev mode and have some problems inside storybook. Please follow the readme to get the error in reproduction.

## Additional details
1. There is a working example with another nuxt-vuetify module (not maintained anymore): https://github.com/storybook-vue/storybook-nuxt-starter
2. I've also left the comment in storybook-nuxt repo
https://github.com/storybook-vue/storybook-nuxt/issues/42#issuecomment-1877067150

**Comment by userquin** [comment]
Vuetify components seems to be loaded without defaults, I'm checking if there is a problem with vuetify post plugin in the vuritfy module and storybook.

FYI: I don't see any page using any Vuetify component in https://github.com/storybook-vue/storybook-nuxt-starter

**Comment by userquin** [comment]
I don't now why `applyNuxtPlugins` are called after rendering the pages, I just added a breakpoint in the nuxtjs/i18n warning, storybook should review Nuxt 3 integration logic.

This module enables treeshaking feature via vuetify vite plugin (there is no way to use all components, you need to add them to `vuetify.vuetifyOptions.components` in the nuxt configuration or vuetify config file), the deprecated nuxt module by default not enabling that feature IIRC (maybe also a problem with nuxt vuetify `sequential post` plugin, `i18n` is present and enabled in the app).

**Comment by AndreyYolkin** [comment]
> FYI: I don't see any page using any Vuetify component in https://github.com/storybook-vue/storybook-nuxt-starter

Of course, here is the direct link to component:
https://github.com/storybook-vue/storybook-nuxt-starter/blob/master/components/vuetify/index.vue

And Story:
https://github.com/storybook-vue/storybook-nuxt-starter/blob/master/stories/Vuetify.stories.ts

**Comment by userquin** [comment]
If you run the dev server, you can see vuetify components imports at the bottom:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/cf537601-10d1-49e2-9943-3ca6e1e4eade)

Same component in storebook (missing imports):

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/f1bf3b0e-867c-4e9f-877f-5ea92c51dd69)

**Comment by userquin** [comment]
The i18n module seems to be fine, so the problem should be in storebook: it seems it is building the project but I have no idea what's doingbehing the scenes: the vuetify vite plugin is registered manually by this module and injects the vuetify imports parsing the vue file in the vite plugins pipeline.

**Comment by AndreyYolkin** [comment]
Reproduction repo also has story, where I defined imports manually, but in that case I get `Could not find defaults instance` issue. I suppose it also happens because nuxt plugin runs too late
<img width="543" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/11289484/c93d163b-c114-457b-b23a-420cbb3c3180">

**Comment by userquin** [comment]
> This module enables treeshaking feature via vuetify vite plugin (there is no way to use all components, you need to add them to `vuetify.vuetifyOptions.components` in the nuxt configuration or vuetify config file), the deprecated nuxt module by default not enabling that feature IIRC (maybe also a problem with nuxt vuetify `sequential post` plugin, `i18n` is installed and configured in the app).

It is about global components: check this entry https://vuetifyjs.com/en/features/treeshaking/

**Comment by userquin** [comment]
> I suppose it also happens because nuxt plugin runs too late

No, it seems vuetify vite plugin missing from vite plugins.

**Comment by AndreyYolkin** [comment]
Ok, thank you for your answers, I'll move on with investigation in storybook ❤️

**Comment by userquin** [comment]
This plugin should add the imports (a copy/paste from the original): https://github.com/userquin/vuetify-nuxt-module/blob/main/src/vite/vuetify-import-plugin.ts#L25-L49

I'm going to check if being called when running `nr storebook`, and check what's running storebook, the dev server or the build.

First time I use storebook ;)

**Comment by AndreyYolkin** [comment]
Me too, honestly. Part of big Nuxt2/3 migration

**Comment by userquin** [comment]
Using `pnpm dev`:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/5393e1d7-1c07-4074-a6ce-f4937141dc01)

**Comment by userquin** [comment]
Running `pnpm storybook` (missing trace):

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/2fee2b63-c7c9-48fa-9db8-95e1e6935d14)

**Comment by userquin** [comment]
Anyway, there is no entry for Nuxt 3 in the docs, with nuxt modules you can do a lot of things, you have layers, you have module hooks (communication between modules), storybook cannot use only vite, Nuxt 3 is built on top of Nitro and Vite

**Comment by userquin** [comment]
It seems we need to patch or use another plugin, the plugin being called but storybook maybe adding some vite plugin to transform vue files.

**Comment by AndreyYolkin** [comment]
I think I will dive into [storybook-nuxt](https://github.com/storybook-vue/storybook-nuxt) internals

**Comment by userquin** [comment]
it is being called in the build, it works, the imports are there, but storybook calling again with raw vue file:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/d443a42e-5f1a-4042-a0ab-e99c61ffdd37)

**Comment by userquin** [comment]
In build:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/98249494-0967-4422-8e8b-96b3d3749922)

**Comment by userquin** [comment]
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/59daab28-6317-4804-982e-e6b548850be2)

**Comment by userquin** [comment]
why building to request raw file?

**Comment by userquin** [comment]
ok, found the problem: https://github.com/storybook-vue/storybook-nuxt/blob/main/packages/storybook-nuxt/src/preset.ts#L95C26-L97

calling with raw vue file since it is moving all plugins before vue

**Comment by AndreyYolkin** [comment]
Oh, I was near, but moved into main storybook repo.

We can modify vite config back by using viteFinal inside `.storybook/main.ts`

```
import type { StorybookConfig } from "@storybook-vue/nuxt";
import {ViteConfig} from "@nuxt/schema";

const config: StorybookConfig = {
  stories: [
    "../stories/**/*.mdx",
    "../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook-vue/nuxt",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
  viteFinal: (config: ViteConfig) => {
    console.log(config.plugins?.map(p => p.name));
    return config
  }
};
export default config;
```

**Comment by userquin** [comment]
No, it is better to use an object notation for the transform hook using enforce/order 'post'

**Comment by userquin** [comment]
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/ca141ce0-05e0-412a-9afa-a6585b8bc829)

**Comment by AndreyYolkin** [comment]
I've achieved the same result rn with this:
![image](https://github.com/userquin/vuetify-nuxt-module/assets/11289484/36e8c570-caca-49ca-aa92-e34c8fa0110f)

**Comment by userquin** [comment]
adding `enforce: 'post'`:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/58bc7fdd-cadb-47f4-bb2d-51822c386d65)

**Comment by userquin** [comment]
I'm going to update the repo to `^7.6.7` :fingers_crossed:

**Comment by userquin** [comment]
no luck:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/22910387-c7d6-4204-bb3b-687738da2692)

**Comment by AndreyYolkin** [comment]
tried too, unluko

**Comment by userquin** [comment]
The pages and components being rendered before vuetify is created providing the defaults (`createVuetify` in vuetify fw module)

**Comment by AndreyYolkin** [comment]
But AFAIK, all plugins runs before components rendering 🫨

**Comment by userquin** [comment]
Tried also using defineAsyncComponent, no luck, same error:

```ts
const Vuetify = defineAsyncComponent({
  loader: () => import('~/components/vuetify/index.vue').then(m => m.default ?? m),
  loadingComponent: () => h('div', 'loading...'),
  onError(error, retry, fail, attempts) {
    console.error('Vuetify::error', error)
  },
})
const VuetifyWithImports = defineAsyncComponent({
  loader: () => import('~/components/vuetify/withImports.vue').then(m => m.default ?? m),
  loadingComponent: () => h('div', 'loading...'),
  onError(error, retry, fail, attempts) {
    console.error('VuetifyWithImports::error', error)
  },
})
```

**Comment by userquin** [comment]
The example using vuetify in storybook not working, in fact, not working even in dev server with latest vuetify, vite and storybook versions: https://github.com/storybookjs/vue3-code-examples

**Comment by userquin** [comment]
@AndreyYolkin using the deprecated vuetify module working with latest vuetify, nuxt, vite and storybook versions?

**Comment by AndreyYolkin** [comment]
Will try tomorrow, not sure, because it was released even before vuetify 3.4 and nuxt 3.7

**Comment by AndreyYolkin** [comment]
Tried with timeout, but still got missing defaults

<img width="705" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/11289484/daa5cd20-c882-4ce7-aaef-72850130dc1b">

**Comment by AndreyYolkin** [comment]
Meanwhile, the deprecated module:

https://github.com/AndreyYolkin/storybook-vuetify-issue/tree/invictus

<img width="1728" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/11289484/332e1a64-65dd-47d3-a9dc-c5cb45409453">

**Comment by chakAs3** [comment]
> Vuetify components seems to be loaded without defaults, I'm checking if there is a problem with vuetify post plugin in this module and storybook.
> 
> FYI: I don't see any page using any Vuetify component in https://github.com/storybook-vue/storybook-nuxt-starter

I have released  @storybook-vue/nuxt 0.2.1 with patch  fixing this issue,.

**Comment by AndreyYolkin** [comment]
> if it did not work for you please create a repro repo for me. i will check it out

I've updated the repo's deps to the latest version, but problem still exists. Please, check the main branch at https://github.com/AndreyYolkin/storybook-vuetify-issue

**Comment by AndreyYolkin** [comment]
https://github.com/vuetifyjs/vuetify/blob/26c72b3601b12531498cd47297f8565de49496c1/packages/vuetify/src/composables/theme.ts#L306

I've tried to remove manipulation with usehead and keep only old approach and it's worked 

```js
  function install(app) {
    if (parsedOptions.isDisabled) return;
    // const head = app._context.provides.usehead;
    // if (head) {
    //   if (head.push) {
    //     const entry = head.push(getHead);
    //     if (IN_BROWSER) {
    //       watch(styles, () => {
    //         entry.patch(getHead);
    //       });
    //     }
    //   } else {
    //     if (IN_BROWSER) {
    //       head.addHeadObjs(computed(getHead));
    //       watchEffect(() => head.updateDOM());
    //     } else {
    //       head.addHeadObjs(getHead());
    //     }
    //   }
    // } else {
      let styleEl = IN_BROWSER ? document.getElementById('vuetify-theme-stylesheet') : null;
      if (IN_BROWSER) {
        watch(styles, updateStyles, {
          immediate: true
        });
      } else {
        updateStyles();
      }
      function updateStyles() {
        if (typeof document !== 'undefined' && !styleEl) {
          const el = document.createElement('style');
          el.type = 'text/css';
          el.id = 'vuetify-theme-stylesheet';
          if (parsedOptions.cspNonce) el.setAttribute('nonce', parsedOptions.cspNonce);
          styleEl = el;
          document.head.appendChild(styleEl);
        }
        if (styleEl) styleEl.innerHTML = styles.value;
      }
    // }
  }
```

**Comment by antrax-x5** [comment]
Hi, @AndreyYolkin , did you found stable working solution for vuetify-nux-module + storybook ??

**Comment by AndreyYolkin** [comment]
> Hi, @AndreyYolkin , did you found stable working solution for vuetify-nux-module + storybook ??

Hi, I ended up with writing own "storybook". I's not so hard, especially if you don't want to automatically get information about slots

**Comment by fredimitchel** [comment]
It seems we have the same issue with Histoire...

https://github.com/histoire-dev/histoire/issues/701

**Comment by fredimitchel** [comment]
Of which library?

**Comment by enzonzee** [comment]
@nuxtjs/storybook v8.0.0

**Comment by jgcarrillo** [comment]
I came across with this issue and the problem still persist.

I don't know wether my problem is related with this issue, but I am using Nuxt 3 with Vuetify 3 and Storybook (@nuxtjs/storybook) and I am having the following error:

```
Failed to build the preview                                                                                                                                                     
Error: Vuetify plugin must be loaded after the vue plugin
```

I think it is because of `vite-plugin-vuetify`.

Any help would be appreciated 🙌🏻

**Comment by tobiasdiez** [comment]
I tried to work on this at https://github.com/nuxt-modules/storybook/pull/614 but got stuck (see PR description there). Would appreciate if someone could take over from here, as I'm not using vuetify myself.
